#include "collision.h"
#include "actor_settings.h"
#include "thwomp_constants.h"
#include <ultra64.h>

u64 testGrid_TXT[] = {
#include "../build/temp/testGrid_TXT.ci4.c"
};

u64 testGrid_TLUT[] = {
#include "../build/temp/testGrid_TLUT.rgba16.c"
};

Vtx test_gridVtx_000820[] = {
#include "test_gridVtx_000820.vtx.inc"
};

Gfx testGrid_DL_1[] = {
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsSPClearGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPSetGeometryMode(G_CULL_BACK | G_FOG | G_LIGHTING),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal256(testGrid_TLUT),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsDPNoOpTag(COLL_TYPE_FLOOR | FOOTSTEP_SFX_STONE),
    gsDPLoadTextureBlock_4b(testGrid_TXT, G_IM_FMT_CI, 64, 64, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP,
                            6, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetPrimColor(0, 0, 153, 153, 153, 255),
    gsSPVertex(&test_gridVtx_000820[84], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsDPPipeSync(),
    gsDPNoOpTag(COLL_TYPE_WALL | FOOTSTEP_SFX_STONE),
    gsSPVertex(&test_gridVtx_000820[36], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsDPPipeSync(),
    gsDPNoOpTag(COLL_TYPE_WALL | FOOTSTEP_SFX_STONE),
    gsSPVertex(&test_gridVtx_000820[60], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsDPPipeSync(),
    gsDPNoOpTag(COLL_TYPE_CEILING | FOOTSTEP_SFX_STONE),
    gsSPVertex(test_gridVtx_000820, 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsSPEndDisplayList(),
};

Gfx testGrid_DL_2[] = {
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsSPClearGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPSetGeometryMode(G_CULL_BACK | G_FOG | G_LIGHTING),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal256(testGrid_TLUT),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsDPNoOpTag(COLL_TYPE_FLOOR | FOOTSTEP_SFX_STONE),
    gsDPLoadTextureBlock_4b(testGrid_TXT, G_IM_FMT_CI, 64, 64, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP,
                            6, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetPrimColor(0, 0, 153, 153, 153, 255),
    gsSPVertex(&test_gridVtx_000820[88], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsDPPipeSync(),
    gsDPNoOpTag(COLL_TYPE_WALL | FOOTSTEP_SFX_STONE),
    gsSPVertex(&test_gridVtx_000820[40], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsDPPipeSync(),
    gsDPNoOpTag(COLL_TYPE_CEILING | FOOTSTEP_SFX_STONE),
    gsSPVertex(&test_gridVtx_000820[4], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsSPEndDisplayList(),
};

Gfx testGrid_DL_3[] = {
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsSPClearGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPSetGeometryMode(G_CULL_BACK | G_FOG | G_LIGHTING),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal256(testGrid_TLUT),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsDPNoOpTag(COLL_TYPE_FLOOR | FOOTSTEP_SFX_STONE),
    gsDPLoadTextureBlock_4b(testGrid_TXT, G_IM_FMT_CI, 64, 64, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP,
                            6, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetPrimColor(0, 0, 153, 153, 153, 255),
    gsSPVertex(&test_gridVtx_000820[92], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsDPPipeSync(),
    gsDPNoOpTag(COLL_TYPE_WALL | FOOTSTEP_SFX_STONE),
    gsSPVertex(&test_gridVtx_000820[44], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsDPPipeSync(),
    gsDPNoOpTag(COLL_TYPE_CEILING | FOOTSTEP_SFX_STONE),
    gsSPVertex(&test_gridVtx_000820[8], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsSPEndDisplayList(),
};

Gfx testGrid_DL_4[] = {
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsSPClearGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPSetGeometryMode(G_CULL_BACK | G_FOG | G_LIGHTING),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal256(testGrid_TLUT),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsDPNoOpTag(COLL_TYPE_WALL | FOOTSTEP_SFX_STONE),
    gsDPLoadTextureBlock_4b(testGrid_TXT, G_IM_FMT_CI, 64, 64, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP,
                            6, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetPrimColor(0, 0, 153, 153, 153, 255),
    gsSPVertex(&test_gridVtx_000820[64], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsSPEndDisplayList(),
};

Gfx testGrid_DL_5[] = {
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsSPClearGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPSetGeometryMode(G_CULL_BACK | G_FOG | G_LIGHTING),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal256(testGrid_TLUT),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsDPNoOpTag(COLL_TYPE_FLOOR | FOOTSTEP_SFX_STONE),
    gsDPLoadTextureBlock_4b(testGrid_TXT, G_IM_FMT_CI, 64, 64, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP,
                            6, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetPrimColor(0, 0, 153, 153, 153, 255),
    gsSPVertex(&test_gridVtx_000820[96], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsDPPipeSync(),
    gsDPNoOpTag(COLL_TYPE_WALL | FOOTSTEP_SFX_STONE),
    gsSPVertex(&test_gridVtx_000820[68], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsDPPipeSync(),
    gsDPNoOpTag(COLL_TYPE_CEILING | FOOTSTEP_SFX_STONE),
    gsSPVertex(&test_gridVtx_000820[12], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsSPEndDisplayList(),
};

Gfx testGrid_DL_6[] = {
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsSPClearGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPSetGeometryMode(G_CULL_BACK | G_FOG | G_LIGHTING),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal256(testGrid_TLUT),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsDPNoOpTag(COLL_TYPE_FLOOR | FOOTSTEP_SFX_STONE),
    gsDPLoadTextureBlock_4b(testGrid_TXT, G_IM_FMT_CI, 64, 64, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP,
                            6, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetPrimColor(0, 0, 153, 153, 153, 255),
    gsSPVertex(&test_gridVtx_000820[100], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsDPPipeSync(),
    gsDPNoOpTag(COLL_TYPE_CEILING | FOOTSTEP_SFX_STONE),
    gsSPVertex(&test_gridVtx_000820[16], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsSPEndDisplayList(),
};

Gfx testGrid_DL_7[] = {
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsSPClearGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPSetGeometryMode(G_CULL_BACK | G_FOG | G_LIGHTING),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal256(testGrid_TLUT),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsDPNoOpTag(COLL_TYPE_FLOOR | FOOTSTEP_SFX_STONE),
    gsDPLoadTextureBlock_4b(testGrid_TXT, G_IM_FMT_CI, 64, 64, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP,
                            6, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetPrimColor(0, 0, 153, 153, 153, 255),
    gsSPVertex(&test_gridVtx_000820[104], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsDPPipeSync(),
    gsDPNoOpTag(COLL_TYPE_CEILING | FOOTSTEP_SFX_STONE),
    gsSPVertex(&test_gridVtx_000820[20], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsSPEndDisplayList(),
};

Gfx testGrid_DL_8[] = {
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsSPClearGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPSetGeometryMode(G_CULL_BACK | G_FOG | G_LIGHTING),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal256(testGrid_TLUT),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsDPNoOpTag(COLL_TYPE_WALL | FOOTSTEP_SFX_STONE),
    gsDPLoadTextureBlock_4b(testGrid_TXT, G_IM_FMT_CI, 64, 64, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP,
                            6, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetPrimColor(0, 0, 153, 153, 153, 255),
    gsSPVertex(&test_gridVtx_000820[72], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsSPEndDisplayList(),
};

Gfx testGrid_DL_9[] = {
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsSPClearGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPSetGeometryMode(G_CULL_BACK | G_FOG | G_LIGHTING),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal256(testGrid_TLUT),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsDPNoOpTag(COLL_TYPE_FLOOR | FOOTSTEP_SFX_STONE),
    gsDPLoadTextureBlock_4b(testGrid_TXT, G_IM_FMT_CI, 64, 64, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP,
                            6, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetPrimColor(0, 0, 153, 153, 153, 255),
    gsSPVertex(&test_gridVtx_000820[108], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsDPPipeSync(),
    gsDPNoOpTag(COLL_TYPE_WALL | FOOTSTEP_SFX_STONE),
    gsSPVertex(&test_gridVtx_000820[76], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsDPPipeSync(),
    gsDPNoOpTag(COLL_TYPE_CEILING | FOOTSTEP_SFX_STONE),
    gsSPVertex(&test_gridVtx_000820[24], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsSPEndDisplayList(),
};

Gfx testGrid_DL_10[] = {
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsSPClearGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPSetGeometryMode(G_CULL_BACK | G_FOG | G_LIGHTING),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal256(testGrid_TLUT),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsDPNoOpTag(COLL_TYPE_FLOOR | FOOTSTEP_SFX_STONE),
    gsDPLoadTextureBlock_4b(testGrid_TXT, G_IM_FMT_CI, 64, 64, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP,
                            6, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetPrimColor(0, 0, 153, 153, 153, 255),
    gsSPVertex(&test_gridVtx_000820[112], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsDPPipeSync(),
    gsDPNoOpTag(COLL_TYPE_CEILING | FOOTSTEP_SFX_STONE),
    gsSPVertex(&test_gridVtx_000820[28], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsSPEndDisplayList(),
};

Gfx testGrid_DL_11[] = {
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsSPClearGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPSetGeometryMode(G_CULL_BACK | G_FOG | G_LIGHTING),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal256(testGrid_TLUT),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsDPNoOpTag(COLL_TYPE_FLOOR | FOOTSTEP_SFX_STONE),
    gsDPLoadTextureBlock_4b(testGrid_TXT, G_IM_FMT_CI, 64, 64, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP,
                            6, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetPrimColor(0, 0, 153, 153, 153, 255),
    gsSPVertex(&test_gridVtx_000820[116], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsDPPipeSync(),
    gsDPNoOpTag(COLL_TYPE_CEILING | FOOTSTEP_SFX_STONE),
    gsSPVertex(&test_gridVtx_000820[32], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsSPEndDisplayList(),
};

Gfx testGrid_DL_12[] = {
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsSPClearGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPSetGeometryMode(G_CULL_BACK | G_FOG | G_LIGHTING),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal256(testGrid_TLUT),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsDPNoOpTag(COLL_TYPE_WALL | FOOTSTEP_SFX_STONE),
    gsDPLoadTextureBlock_4b(testGrid_TXT, G_IM_FMT_CI, 64, 64, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP,
                            6, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetPrimColor(0, 0, 153, 153, 153, 255),
    gsSPVertex(&test_gridVtx_000820[80], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsSPEndDisplayList(),
};

Gfx testGrid_DL_13[] = {
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsSPClearGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPSetGeometryMode(G_CULL_BACK | G_FOG | G_LIGHTING),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal256(testGrid_TLUT),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsDPNoOpTag(COLL_TYPE_WALL | FOOTSTEP_SFX_STONE),
    gsDPLoadTextureBlock_4b(testGrid_TXT, G_IM_FMT_CI, 64, 64, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP,
                            6, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetPrimColor(0, 0, 153, 153, 153, 255),
    gsSPVertex(&test_gridVtx_000820[48], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsSPEndDisplayList(),
};

Gfx testGrid_DL_14[] = {
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsSPClearGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPSetGeometryMode(G_CULL_BACK | G_FOG | G_LIGHTING),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal256(testGrid_TLUT),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsDPNoOpTag(COLL_TYPE_WALL | FOOTSTEP_SFX_STONE),
    gsDPLoadTextureBlock_4b(testGrid_TXT, G_IM_FMT_CI, 64, 64, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP,
                            6, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetPrimColor(0, 0, 153, 153, 153, 255),
    gsSPVertex(&test_gridVtx_000820[52], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsSPEndDisplayList(),
};

Gfx testGrid_DL_15[] = {
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsSPClearGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPSetGeometryMode(G_CULL_BACK | G_FOG | G_LIGHTING),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal256(testGrid_TLUT),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsDPNoOpTag(COLL_TYPE_WALL | FOOTSTEP_SFX_STONE),
    gsDPLoadTextureBlock_4b(testGrid_TXT, G_IM_FMT_CI, 64, 64, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP,
                            6, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetPrimColor(0, 0, 153, 153, 153, 255),
    gsSPVertex(&test_gridVtx_000820[56], 4, 0),
    gsSP2Triangles(2, 1, 0, 0, 3, 2, 0, 0),
    gsSPEndDisplayList(),
};

// Actor list
const actor_settings actor_list[] = {
    {{-100, 0,  -70},  THWOMP_ACTOR_ID, 40,  40, 1,  01, 00},
    {{-100, 0, -170},  THWOMP_ACTOR_ID, 80,  20, 2,  01, 00},
    {{-100, 0, -310},  THWOMP_ACTOR_ID, 120, 10, 3,  01, 00},
    {{   0, 0,    0},   END_ACTOR_LIST,   0,  0,  0,  0x80, 00}     // "End of actor list" marker
};
